services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - backend_static:/app/static
    environment:
      - DEBUG=True
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: python manage.py runserver 0.0.0.0:8000

  dashboard:
    build:
      context: ./backend/dashboard
      dockerfile: Dockerfile
    volumes:
      - ./backend/dashboard:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    restart: unless-stopped
    # Para desarrollo:
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - BACKEND_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    command: npm run dev

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  backend_static: